### PR TITLE
French localisation of mem_imperialist_intimidation_modifiers

### PR DESCRIPTION
**Pull request by MrQuality97**
A French localisation of this file. Hopefully this time it's something that's still in the mod. The encoding in this file may not be correct, it might be encoded as UTF-8, without BOM.

### CODE REVIEW

**Comment by Tuttu** [comment]
Yep, this one still in the mod. Don't translate the brain worm if you find it, that's all. :)

**Comment by MrQuality97** [comment]
Okay, no problem. Apart from that is it good to go?

**Comment by Tuttu** [comment]
Yep. Only sk_war, sk_events and the brain worm crisis have been removed. :)

**Comment by tzerrell** [comment]
Hmm, this didn't load in the correct folder (`localisation/`) -- instead it was in the root folder with the word "localisation" at the front of its name. This may be a difficulty with github upload mechanisms -- a number of other people have had filename issues as well. What method are you using to put your files on github? (web interface, GitHub Desktop, or command line git?)

Also, when adding files, try to leave the English file unchanged and just add a French file, rather than replacing the English file with a French file.

These are small things, so I merged your pull request and made a follow-up commit addressing them. I'm just mentioning them so you know what to look out for in the future.

**Comment by MrQuality97** [comment]
Apologies, overwriting the English file with a French one is thoughtless.
To answer your question, I've been using the Web interface.

**Comment by tzerrell** [comment]
Thanks for the information; the web interface has caused multiple issues with files in folders loading incorrectly. Not much to do at this point but hope it goes away. Well, that and also collect information on when it happens in the hope of learning what's going wrong.

Thanks for your translation!

**Pull request merged**
