### PR TITLE
Issue #32 Plus more

### PR DESCRIPTION
**Pull request by binaryferret**
Copy from commit
- Fixes address issue #32 and others  …
- Removed num_commnuications > 7 check on the first event. As the flow of
  the event means that you can have this event even if you don't have any
  communications with other races. You can just choose the option to have
  it for yourselves as per original idea.
  See option name = mem_sciencecon.1.b
- Fixed typos in mem_sciencecon.8.desc
  - Said GameName instead of GetName
  - replaced ` character with ' character.
  - replaced Root.GetName with invite_sender.GetName

### CODE REVIEW

**Comment by P-aul** [comment]
I feel this changes are ok, but would like to get another opinion before merging. Can someone who worked on this/analyzed it comment on whether the changes (previous and this) will improve it?

**Comment by binaryferret** [comment]
Are ok? All the changes commited fix the issues that were reported.

I suppose the only thing I have changed that isn't a fix is the requirement for comms with other empires on the first event. This is due to the fact  that the original event idea and implementation meant that you could run this event without inviting other races - hench the two options (have the event for yourself, or invite other races). 

If the idea has changed so it should only include other aliens and yourself then there is a redundant option in the code.

**Comment by P-aul** [comment]
Well, the original report pointed out that (minus localisation issues) there were some problems with event flow - it spawned to often, races that hated you still would join the con etc... I didn't expect to improve everything and I know there were already some changes done before (increased mtth) and would just like another opinion on how it all works together... 

Actually I still have one issue - when the event spawned for me I didn't feel that one of the options is to make the con just for myself. This could be improved in the future. 

Finally don't take it personally, we (as in admins) are implementing stricter quality assurance for all changes because until now we let to many bugs slip. That means no change will be merged without some additional thinking ;)

**Comment by binaryferret** [comment]
Oh I didn't take it personally. I was just going from the issues reported in the issues tracker. 

Spawning too often was fixed by lamil.
The fixes I implemented are the ones reported in the issues tracker, and the image that Mathius pointed to me. 

Everything else mentioned is a change/addition of functionality, and wasn't in the issue tracker. So I didn't know about those. 

Thus in my head once the issues reported were squished and tested by the implementor then it was to be pushed to the Beta branch for further testing. 

A misunderstanding by how it works, I'm happy for others to further check the diff between the merges etc and test before hand.

**Comment by tzerrell** [comment]
Does Stellaris allow decimal amounts of energy/minerals/influence? If so, this fix may not correctly handle users with e.g. 249.7 minerals. Unless stellaris scripting does not have a >= test, I think that would be preferable.

Other than that the patch looks great!

**Pull request merged**
