### PR TITLE
French translation of "localisations_war_events"

### PR DESCRIPTION
**Pull request by MrQuality97**
My translation of this particular file. As this is my first translated file, please let me know if this is okay and I should translate the other files in the same way as this one.

### CODE REVIEW

**Comment by tzerrell** [comment]
So 5 things (there are lots of details in creating localisation files):
1. The `spanish-loc` branch does not appear to be up-to-date. This file isn't in the mod any more. Sorry about that :(, I'll make sure to update it.
2. Since a `french-loc` branch did not yet exist, I created one for you to submit translations to. It currently has the most up-to-date version of our mod, so no problems with files that shouldn't be there if you work from that branch :)
3. You'll need to change the first line of the file from `l_english:` to `l_french:`
4. The file should be put in the localisation folder, and its name should be the same as the english name except with "french" in place of "english". So for example `mem_some_file_l_english.yml` should be saved as `mem_some_file_l_french.yml` once you have translated it.
5. The file needs to be encoded in UTF-8 with BOM. Yours is encoded as UTF-8 without BOM. If you don't know how to do this, that's ok, just make a note in your pull request that the encoding might be wrong. That way someone can check it and fix it if necessary.

Other than that, this looks great (well, as far as this non-french-speaker can tell :P). Thanks!

**Comment by MrQuality97** [comment]
Okay, I'll bear these things in mind and have another go. Thank you for
your patience with me - I'm a total novice to this, and thank you as well
for letting me be a part of your project :)

**Comment by tzerrell** [comment]
It can take a bit to get up to speed with Stellaris loc and GitHub, and I'm glad to help you get started. Welcome aboard!

**Comment by Tuttu** [comment]
The main issue here is that sk_war is not in the mod anymore. :(

**Pull request closed without merging**
