### PR TITLE
Change Log proposal.

### PR DESCRIPTION
**Pull request by nCrazed**
# Change Log Proposal
## Introduction

This PR proposes the introduction of a human readable change log file into the development process of the mod. Specifically a `CHANGELOG.md` file that should be tracked by git and updated along with changes being made to the mod.

The file should follow the formatting and layout guidelines of [Keep a CHANGELOG v0.3.0](http://keepachangelog.com/en/0.3.0/).
## TODO
- [ ] Migrate all changelogs from wiki to `CHANGELOG.md`
- [ ] Define all heuristics to be used for detecting missing change log entries
- [ ] Decide on the language to use for the implementation. This should be something that most core contributors can understand and maintain.)
#### Simpler release process easier

The current release process involves the person building the next release manually going through the git log since the last release and compiling the changes relevant to the end-users. This is a tedious and an error-prone task that makes the build process longer than it should be.

Having a dedicated file in the source control for this allows shifting the burden of compiling the changes to someone more qualified to describe the change that are being made - the author of the changes.
#### Automated enforcement

There are currently change log pages in the repository's wiki. These pages are updated separately from the mod's code which makes it hard to automatically detect when they become out-dated.

Having user-friendly descriptions of changes that follow a specific format committed along with the changes (This is different from commit messages that serve a different purpose) allows us to check that the change log is updated along with the changes that were made based on various heuristics.

e.g. If a new event file is added, but the author forgot to add a line containing the word `event` to the `[Added]` section of the `Unreleased` version, the author of the changes can be automatically notified and asked to correct the mistake.
### Ensuring that changes are maintained

There are multiple ways to performance automatic checks for missing change log updates.
#### Pull Requests

Ideally I would propose to switch the mod's development process from the current merge-to-`dev`
approach to using pull requests instead. This would allow us to make use of the [PullRequestEvent](https://developer.github.com/v3/activity/events/types/#pullrequestevent) and have all the change log related notifications happen in the pull-request's comments.
#### Merge workflow

Since switching to pull requests is currently out of the question due to various reasons. The automation will have to be done after a branch is merged into the `dev` branch via something like the [PushEvent](https://developer.github.com/v3/activity/events/types/#pushevent) on the `dev` branch. This leaves us with no obvious way to notify the author that they might be missing a change log entry (I expect there will be some false positives).

One way to solve this would be to integrate with a discord bot that would highlight the user there, but this would require a reliable GitHub to Discord user account mapping.

Alternatively, we could automatically open a new issue on GitHub with the author of the changes assigned to it.
### Implementation

The whole thing can be broken in three distinct processes separated by queues:
- Event parser polls the GitHub API for new push events to the `dev` branch. This should cover both merges and people committing directly into the branch. Any new events are then written to the `input` queue with all the necessary meta data.
- Change parser reads data from the `input` queue and passes it on to all registered heuristics. If a change without an appropriate updated to `CHANGELOG.md` is detected, the necessary information is written to the `output` queue.
- Notifier reads data from the `output` queue and passes it on to GitHub, Discord or any other notification mechanism we decide to employ.

_My personal preference here would be to use Python. As for the queue back-end, initial prototype could simply use an SQLite database which can be replaced with something more appropriate at a later time._
### Hosting

Obviously this would have to be hosted somewhere, ideally without any monetary cost.
- Someone could host this on their existing infrastructure (I have a couple VPS instances with spare resources that I could dedicate to this).
- Since the development and testing would be handled within a virtual machine manager by [Vagrant](https://www.vagrantup.com/), someone could leverage this to run a "production" vm on their own hardware.
### Additional features

Regardless on how we decide to implement this, we can then piggy-back on the functionality to automate other tasks.

For some changes it makes sense to inform a group of people other than the author that they should take a look at the changes and act upon them. 

e.g. If a writer makes changes to an English localisation file, translators can be informed that the file might be ready for them to translate.

### CODE REVIEW

**Comment by nCrazed** [comment]
I will be converting the wiki changelog pages into the keepachangelog format and adding them to the `CHANGELOG.md` over the next couple of days as well as updating the proposal based on the feedback I receive here and on discord.

**Comment by tzerrell** [comment]
Thank you for putting this together, this looks excellent.

Adding a changelog file in the format described in the article sounds great and I see no reason not to merge our previous changelogs and current Unreleased changes into `CHANGELOG.md` immediately.

The automated alerts is the trickier part of this proposal, both from a technical perspective and from a social/workflow perspective. My experience has been that team members inexperienced with git found the merge workflow that we are currently using much simpler to understand and use than the pull request workflow we used to use. Two key features that appeared to have made the merge workflow easier are:
- No need to distinguish the main MEM repo from their personal repo
- No need to understand branching immediately; new users initially make small commits to `dev` and once they are used to the system they can easily transition into using their own branches for larger works (i.e. new events rather than bugfixes and tweaks).

Unfortunately that workflow is a bit more technically challenging (or at least inelegant); I think if there were no learning curve issues a pull request workflow would be better for the mod in general. That said, we could presumably set up the automation using PushEvent to add a comment to the newly pushed commit (or the most recent pushed commit if there are multiple pushed). I think this is not quite as nice as a PR comment insofar as it is necessarily retroactive, but I think it would still work reasonably well.

A Discord bot would certainly be cool, but might be more effort than it's worth to implement.

Heuristics to consider:
- Was a file added or deleted?
- Was a file modified by more than (say) 10 lines?
- more?

We could pair these with whether specific changes were made to `CHANGELOG.md` but just checking that the change log was edited at all might be good enough.

Language:
- I have essentially no experience with web development and don't have a strong opinion.

**Comment by nCrazed** [comment]
@tzerrell The only part of the bot that could be interpreted as related to web development is having to interact with GitHub (and possibly Discord) APIs over HTTP(S).

I've added _Implementation_ and hosting _Hosting_ sections to clear things up.

**Comment by tzerrell** [comment]
Ah, gotcha. I looked at github's API tutorial materials, saw ruby and some scripting language I'd never heard of (curl), and thought it was probably a bunch of webdev stuff.

Python sounds great, but I'm comfortable in a variety of vaguely C-syntax languages (C++, C, Java, Python, etc)

**Comment by tzerrell** [comment]
The automation seems to not be going anywhere, so I'm closing this. I do support having a changelog, so I'm planning on adding one manually that we can manually update.

**Pull request closed without merging**
